### ISSUE TITLE
[要望] 自動的な非表示・表示（経過時間など）

### ISSUE THREAD

**Issue by horyu501** [PermanentWave/SetTopAndBottomButtons#1]
公開ありがとうございます。便利に使っています。  
要望ですが、停止状態などで一定時間そのままの場合にはボタンが自動的に非表示になる、スクロールし始めたらまた表示する、といった動作をしてくれるととうれしいです。

**Comment by PermanentWave** [comment]
ご意見ありがとうございます。
是非実装したいのですが、私はプログラミング初心者ですので、(実力不足により)完成できないor公開まで少々お時間頂く場合がございます。
あらかじめご了承願います。

**Comment by horyu501** [comment]
返答ありがとうございます。

**Comment by PermanentWave** [comment]
お世話になっております。
本日、ボタンの自動非表示機能を実装したバージョンアップを行いました。
申し訳ありませんが、自身の使い勝手の観点から自動非表示は2秒後とさせていただきます。(今後変更の可能性があります。)
26行目のvarIdleTimeOutの値を変更することで時間調節が可能ですので、お使いの環境にそぐわない場合はお手数ですが、本スクリプトをローカルに保存いただき、ご自身で調整をお願いいたします。

今回の機能追加は大変勉強になりました。ご意見ありがとうございました。今後もお使いいただければ幸いです。

**Comment by horyu501** [comment]
実装感謝いたします。
調整の説明もありがとうございます。
